### PR TITLE
[VIS-1061] Remove vision code

### PR DESCRIPTION
**Pull request by marvrez**
Removes everything related to vision, as the the functionality now exists in V1. See https://cognite-sdk-python.readthedocs-hosted.com/en/latest/cognite.html#vision

## Checklist

- [x] Changelog entry added in `CHANGELOG` or not relevant for this change
- [x] Version updated in `pyproject.toml` or not relevant for this change

### CODE REVIEW

**Review by miladcognite — APPROVED** [review]
LGTM :+1: 
I think we can actually also remove the old tag detection methods as well (but perhaps outside the scope of this PR)

**Comment by marvrez** [comment]
Unstructured search is using the method, so I'm holding off with removing it.

**Comment by miladcognite** [comment]
> Unstructured search is using the method, so I'm holding off with removing it.

Not anymore I believe - am I right @arnels?

**Comment by marvrez** [comment]
Check the fixup commits @miladcognite

**Review by miladcognite — APPROVED** [review]

**Pull request merged**
